### ISSUE TITLE
Instantly kicked

### ISSUE THREAD

**Issue by ritana5** [HowardZHY/ProtocolSupport#5]
When I try to join on any version under 1.8, I get kicked with this error

ritana5 lost connection: Internal Exception: io.netty.handler.codec.EncoderException: io.netty.handler.codec.DecoderException: The received a byte array longer than allowed 61696 > 32767

**Comment by HowardZHY** [comment]
Use any tacospigot fork instead of paper, otherwise you have bad plugin or outdated proxy
